browser=chrome
url=https://www.saucedemo.com/
username=standard_user
password=secret_sauce
wrong_password=^%6768767HG
wrong_username=alihaider
emptyUser=""
emptyPass=""
spaced_username=  standard_user
spaced_password=  secret_sauce
maskedPasswordType=password